name: Deploy Hugo

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "hugo-site-producer/hugo-site-producer"  # 匹配实际嵌套结构
          submodules: false

      - name: Debug
        run: ls -R hugo-site-producer/hugo-site-producer  # 验证路径

      - name: Build
        run: |
          cd hugo-site-producer/hugo-site-producer/blogsite1
          hugo --minify --baseURL "${{ secrets.BASE_URL }}"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo-site-producer/hugo-site-producer/blogsite1/public
          publish_branch: gh-pages