name: Deploy Hugo

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout site
        uses: actions/checkout@v4  # 无需 path 参数
        with:
          path: "."  # 匹配实际嵌套结构
          submodules: false

      - name: Debug
        run: ls -R hugo-site-producer  # 验证检出内容

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: |
          ls -R hugo-site-producer && \
          cd hugo-site-producer/blogsite1 && \
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo-site-producer/blogsite1/public
          publish_branch: gh-page
